spring:
  main:
    allow-circular-references: true
  application:
    name: my-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: application
          # uri: http://localhost:9004/
          uri: lb://aolie-application
          predicates:
            - Path=/menu/**,/page/**,/step/**,/user/**
        - id: core
          uri: lb://aolie-core
          predicates:
            - Path=/core/**,/dm/**,/ui/**,/fixrow/**,/plug/**
        - id: query
          uri: lb://aolie-query
          predicates:
            - Path=/qr/**


    nacos:
      discovery:
        server-addr: 192.168.3.6:8848
  redis:
    port: 6379
    host: 192.168.3.6
    password: root
server:
  port: 80
timing:
  nacos:
    gateway:
      address: 192.168.3.6:8848
      dataId: my-gateway
      groupId: my-gateway
      timeout: 300000
  session:
    secretKey: 879sdf78ds7f98ds7f##4
    timeout: 300000
logging:
  pattern:
    console: "%C:%L %m%n"
dubbo:
  scan:
    base-packages: "com.ranranx.aolie"
  protocol:
    port: 20882
    name: dubbo
    host: 192.168.3.6
  cloud:
    subscribed-services: aolie-application
